export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
// Registrar usuario
export const REGISTRO_USUARIO = 'REGISTRO_USUARIO';
export const REGISTRO_USUARIO_EXITOSO = 'REGISTRO_USUARIO_EXITOSO';
export const REGISTRO_USUARIO_ERROR = 'REGISTRO_USUARIO_ERROR';
export const RESET_AUTH_MESSAGE = 'RESET_AUTH_MESSAGE';
// Login usuario
export const LOGIN_USUARIO = 'LOGIN_USUARIO';
export const LOGIN_USUARIO_EXITOSO = 'LOGIN_USUARIO_EXITOSO';
export const LOGIN_USUARIO_ERROR = 'LOGIN_USUARIO_ERROR';
// Obtener usuario
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const OBTENER_USUARIO_EXITO = 'OBTENER_USUARIO_EXITO';
export const OBTENER_USUARIO_ERROR = 'OBTENER_USUARIO_ERROR;'
// Cerrar sesión
export const CERRAR_SESION = 'CERRAR_SESION';

// Pages
export const GET_HOME = 'GET_HOME';
export const VIDEO_HOME= 'VIDEO_HOME';
export const GET_COURSES = 'GET_COURSES';
export const GET_NOSOTROS = 'GET_NOSOTROS';
export const GET_TEAM = 'GET_TEAM';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_PREMIUM = 'GET_PREMIUM';
export const GET_CONTACTO_PAGE = 'GET_CONTACTO_PAGE'
export const FORM_CONTACT = 'FORM_CONTACT'
export const RESET_FORM_CONTACT = 'RESET_FORM_CONTACT'
export const GET_COURSE = 'GET_COURSE'
export const GET_SECCIONES = 'GET_SECCIONES'
export const GET_LECCIOENS = 'GET_LECCIOENS'
export const GET_LECCIONES_SECTIONES = 'GET_LECCIONES_SECTIONES'
export const SELECT_LECCION = 'SELECT_LECCION'
export const GET_TEACHER = 'GET_TEACHER'
